Create contact form
WildCodeSchool/tours-php-2103-project3-ingescop pull request #12
Opened 2021-06-10 10:04 UTC by StephaneSauvaget

2021-06-10 10:16 UTC, ced37 submitted a review, later dismissed

2021-06-10 10:18 UTC, ThibaultBardinetLanglois approved these changes, later dismissed

2021-06-10 12:43 UTC, RomainClair requested changes
It's a symfony best practice to use an object behind the form. You should use it

2021-06-10 12:43 UTC, RomainClair commented on .env
> +MAILER_DSN=smtp://contact@1gscop.fr
The SMTP server should probably in a .local env because each deployment of the project will probably use it's own SMTP server

2021-06-11 06:09 UTC, ced37 approved these changes

2021-06-11 07:41 UTC, floriane-cheneveau approved these changes

2021-06-11 13:09 UTC, RomainClair approved these changes

2021-06-11 13:09 UTC, RomainClair commented on src/Controller/ContactController.php
> +                ->to('s.sauvaget41000@gmail.com')
This should probably be a parameter and in this particular case probably an environment parameter.
See : https://symfony.com/doc/current/configuration.html#configuration-parameters

2021-06-11 13:10 UTC, merged