Add services
WildCodeSchool/tours-php-2103-project3-ingescop pull request #13
Opened 2021-06-10 12:47 UTC by ThibaultBardinetLanglois

2021-06-10 15:01 UTC, ced37 submitted a review, later dismissed

2021-06-11 07:27 UTC, ced37 approved these changes, later dismissed

2021-06-11 07:35 UTC, StephaneSauvaget approved these changes, later dismissed

2021-06-11 07:39 UTC, floriane-cheneveau submitted a review, later dismissed

2021-06-11 13:23 UTC, RomainClair requested changes
It may not be necessary to have the font licence file and readme in your asset directory.
You should provide different file format for font. Like woff2 for example.
The asset directory is not accessible. You may store your fonts in the public directory or see webpack capabilities for dealing with fonts.

The Version*** (migration) file is not compatible with the actual dev database state.
You must generate a new one that can be apply form the dev state

2021-06-11 13:23 UTC, RomainClair commented on src/Controller/ProfessionnalController.php
> +        $pro = $proRepository->findOneById($id);
findOneById() can be replace by just find()

2021-06-11 15:51 UTC, StephaneSauvaget approved these changes, later dismissed
Nice job! :)

2021-06-11 16:02 UTC, ced37 approved these changes, later dismissed

2021-06-14 07:58 UTC, StephaneSauvaget approved these changes, later dismissed

2021-06-14 07:58 UTC, ced37 approved these changes, later dismissed

2021-06-15 07:38 UTC, RomainClair reviewed
As you use only two font files, you could embed only the needed ones.

2021-06-15 10:26 UTC, ced37 approved these changes

2021-06-15 15:02 UTC, StephaneSauvaget submitted a review, later dismissed

2021-06-15 15:02 UTC, ced37 submitted a review, later dismissed

2021-06-16 07:39 UTC, RomainClair approved these changes

2021-06-16 07:55 UTC, StephaneSauvaget approved these changes

2021-06-16 07:56 UTC, ced37 approved these changes

2021-06-16 08:03 UTC, merged