Create service crud
WildCodeSchool/tours-php-2103-project3-ingescop pull request #27
Opened 2021-06-24 14:50 UTC by StephaneSauvaget

2021-07-02 12:20 UTC, ced37 approved these changes, later dismissed

2021-07-02 13:30 UTC, floriane-cheneveau approved these changes, later dismissed

2021-07-05 09:50 UTC, RomainClair requested changes
All the requirements are missing for route parameters

2021-07-05 09:50 UTC, RomainClair commented on src/Controller/AdminController.php
> +     * @Route("/newservice", name="newservice", methods={"GET","POST"})
/service/new may probably be more "readable"

2021-07-05 09:50 UTC, RomainClair commented on src/Controller/AdminController.php
> +            $entityManager = $this->getDoctrine()->getManager();
You should inject the EntityManager as a method parameter

2021-07-05 10:29 UTC, ced37 approved these changes

2021-07-05 10:31 UTC, ThibaultBardinetLanglois approved these changes

2021-07-05 11:09 UTC, RomainClair approved these changes

2021-07-05 11:09 UTC, merged