creation entité service metier
WildCodeSchool/tours-php-2103-project3-ingescop pull request #9
Opened 2021-06-09 14:17 UTC by floriane-cheneveau

2021-06-09 14:19 UTC, ThibaultBardinetLanglois submitted a review, later dismissed

2021-06-09 14:20 UTC, ced37 approved these changes, later dismissed

2021-06-09 14:42 UTC, StephaneSauvaget approved these changes

2021-06-09 14:42 UTC, ced37 approved these changes

2021-06-10 07:13 UTC, closed without merging

2021-06-10 07:13 UTC, RomainClair requested changes
You should have only one naming convention.
You should use english for your identifiers